### ISSUE TITLE
Compile Error with ESPHOME  esphome-2026.8.1

### ISSUE THREAD

**Issue by pfostenberg** [kpfleming/esphome-influxdb_v2_oss#12]
Hi
habe problems after upgrade to esphome-2026.8.1

 In member function 'virtual std::string esphome::influxdb::SensorField::sensor_object_id() const':
esphome/components/influxdb_v2_oss/influxdb.h:124:73: error: 'const class esphome::sensor::Sensor' has no member named 'get_object_id'; did you mean 'get_object_id_to'?
  124 |   std::string sensor_object_id() const override { return this->sensor_->get_object_id(); }
      |                                                                         ^~~~~~~~~~~~~
      |                                                                         get_object_id_to

is the problem on esphome or in this code?

BR

Andreas

**Comment by pfostenberg** [comment]
If I downgrade to pip install esphome==2026.3.0 all works again.

**Comment by kpfleming** [comment]
This problem is caused by lack of maintenance of this project - I moved house some time ago and do not have Home Assistant or ESPHome setup at the new house, so I haven't been using this project and haven't had time to try to keep it up to date.

**Comment by pfostenberg** [comment]
if you add me ... then I can fix it... 

BR

Andreas

**Comment by kpfleming** [comment]
There's no need for you to be 'added'; you can open a PR which includes that change, and the CI checks will test it against the current releases of ESPHome. If it works, I'll merge it and make a release, and be in your debt!

**Comment by pfostenberg** [comment]
ok PR created.

**Comment by pfostenberg** [comment]
Pull Request ist updated. on my side work with 2026.3.0 and 2026.7.0 compile runs on buth versions on my side.

**Comment by kpfleming** [comment]
Resolved in #13.
